services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: retail_pipeline
      POSTGRES_USER: retail_user
      POSTGRES_PASSWORD: retail_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
